name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify Ubuntu version

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (using Temurin distribution for JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Gradle wrapper (if not already configured)
      - name: Set up Gradle wrapper
        run: chmod +x gradlew

      # Build the APK using Gradle
      - name: Build APK
        run: ./gradlew assembleRelease

      # Debug Step: List APK output directory
      - name: Debug - List APK Directory
        run: ls -R app/build/outputs/apk/release/

      # Upload the APK as an artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
