name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Specify Ubuntu version

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (required by Android Gradle plugin)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Gradle wrapper (if not already configured)
      - name: Set up Gradle wrapper
        run: chmod +x gradlew

      # Build the APK using Gradle
      - name: Build APK
        run: ./gradlew assembleRelease

      # Upload the APK as an artifact (updated to v3)
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
